// examples/react-starter/src/App.js
import React from 'react';

const App = () => (
  <div className="container">
    <h1>Typographist</h1>
    <p>
      The Typographist is a mobile first progressive toolkit for web designers
      and developers that allows you to build interfaces with responsive
      graphics. Having absorbed the best qualities of{' '}
      <a href="https://sassline.com/" target="_blank" rel="noreferrer noopener">
        Sassline
      </a>{' '}
      and{' '}
      <a
        href="https://matejlatin.github.io/Gutenberg/"
        target="_blank"
        rel="noreferrer noopener"
      >
        Gutenberg
      </a>, it significantly simplifies the process of improving typography on
      the web. The framework s objective is to provide developers with the most
      simple, powerful and flexible tool that will take over all the routine
      work in the form of complex calculations. The Typographist builds a basic
      grid to establish the correct vertical rhythm on the basis of rem, and
      also establishes macro-tipography, which allows paying special attention
      to micro-tipographic details. Also the toolkit is perfectly combined with
      css grid layout.
    </p>
  </div>
);

export default App;

// examples/vue-starter/src/components/App.vue


<template>
  <div class="container">
    <h1>Typographist</h1>
    <p>The Typographist is a mobile first progressive toolkit for web
      designers and developers that allows you to build interfaces with
      responsive graphics. Having absorbed the best qualities of
      <a href="https://sassline.com/" target="_blank">Sassline</a> and

      <a href="https://matejlatin.github.io/Gutenberg/" target="_blank">Gutenberg</a>,
      it significantly simplifies the process of improving typography on the web.
      The framework s objective is to provide developers with the most simple,
      powerful and flexible tool that will take over all the routine work in the
      form of complex calculations. The Typographist builds a basic grid to
      establish the correct vertical rhythm on the basis of rem, and also establishes
      macro-tipography, which allows paying special attention to micro-tipographic details.
      Also the toolkit is perfectly combined with css grid layout.</p>
  </div>
</template>

<script>
// eslint disable
export default {
  name: 'Home',
};
</script>
